# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Esta es una prueba de descripcion de mi movida
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: fuck
github_username:  yeah

# Build settings
markdown: jvg

paginate: 6

author: Your name

gems: [jekyll-paginate]
